openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
  description: A simple Pet Store API

paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: Pet ID
        name:
          type: string
          description: Pet name
          minLength: 1
          maxLength: 100
        tag:
          type: string
          description: Pet tag/category
        status:
          type: string
          enum:
            - available
            - pending
            - sold
          description: Pet status
        birthDate:
          type: string
          format: date
          description: Pet birth date
        price:
          type: number
          format: double
          minimum: 0
          description: Pet price

